version: '3'

services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: edbridge-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=edbridge
    networks:
      - edbridge-network

  # Backend service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: edbridge-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/edbridge
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=30d
      - JWT_COOKIE_EXPIRE=30
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=${GROQ_MODEL}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    networks:
      - edbridge-network

  # Frontend service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: edbridge-client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://server:5000/api
    networks:
      - edbridge-network

networks:
  edbridge-network:
    driver: bridge

volumes:
  mongo-data:
